// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxS31sc0F8LNA4qZpPnwPrazFaWeLgUz4',
    appId: '1:586358333020:web:9bc71c2dc34d37185e9099',
    messagingSenderId: '586358333020',
    projectId: 'shopapp-c3328',
    authDomain: 'shopapp-c3328.firebaseapp.com',
    storageBucket: 'shopapp-c3328.appspot.com',
    measurementId: 'G-ELJB7XQCYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnfgw93yIVS0oTlrXwCwyhCbxFqdPh_xo',
    appId: '1:586358333020:android:6310dd88b6b239555e9099',
    messagingSenderId: '586358333020',
    projectId: 'shopapp-c3328',
    storageBucket: 'shopapp-c3328.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSV6h2Kuozb1sYC-A1H_bpbi2tYwCRhvk',
    appId: '1:586358333020:ios:cb4602e6aabf21035e9099',
    messagingSenderId: '586358333020',
    projectId: 'shopapp-c3328',
    storageBucket: 'shopapp-c3328.appspot.com',
    iosClientId: '586358333020-c7252rfl9sk673boninio4e9bdq4qpds.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSV6h2Kuozb1sYC-A1H_bpbi2tYwCRhvk',
    appId: '1:586358333020:ios:cb4602e6aabf21035e9099',
    messagingSenderId: '586358333020',
    projectId: 'shopapp-c3328',
    storageBucket: 'shopapp-c3328.appspot.com',
    iosClientId: '586358333020-c7252rfl9sk673boninio4e9bdq4qpds.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
